---
- name: Testing andrewrothstein.nats
  hosts: all
  vars:
    nats_app: nats-server
    nats_ver: v2.1.0
    nats_checksums:
      v2.1.0:
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-darwin-amd64.zip
        darwin-amd64: sha256:310078d28ecc22019c4e3ff58ff9964fc1a53e10a54e25272cfb0cf20e4e4b82
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-linux-386.zip
        linux-386: sha256:6cbffa31ad5c4baf789ec3a1002e169ff6370458e2f5ba93a2c1c33a90876cf5
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-linux-amd64.zip
        linux-amd64: sha256:a4012cac52715dbc693dbc3a98b90369b132416b12a67f9bcfb24c18d1efcbd6
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-linux-arm6.zip
        linux-arm6: sha256:8d874316f09c4508755c43537e488d1105471290014421f05770738ffdc823d8
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-linux-arm64.zip
        linux-arm64: sha256:85623db85eb908211b6aa0bcd149ebd969c2ace3f6bb1abf9f3564ca82474a40
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-linux-arm7.zip
        linux-arm7: sha256:6c17e5f1ef625ee1063d3c2bde140a6725b6b0f63137c35f6898f49fd06fa584
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-windows-386.zip
        windows-386: sha256:f234a569471540f03cb631315d3f4da6f978e4c217746c5e6518c3a6d564b17d
        # https://github.com/nats-io/nats-server/releases/download/v2.1.0/nats-server-v2.1.0-windows-amd64.zip
        windows-amd64: sha256:186ab39af0c99a9d98c36eb5022fd4d6cd188b96bed8ece0fd88756e56f334c9
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'nats-server --version'
      ansible.builtin.command: /usr/local/nats-server/nats-server --version
      changed_when: false
      register: nats_test_output
    - name: Output of 'nats-server --version'
      ansible.builtin.debug:
        msg: '{{ nats_test_output.stdout }}'
