---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for nats app install in {{ nats_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ nats_install_dir }}'
  changed_when: false
  register: nats_binary
- name: Downloading and installing nats app
  when: not nats_binary.stat.exists
  block:
    - name: Downloading {{ nats_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ nats_url }}'
        dest: '{{ nats_tmp_zip }}'
        mode: '644'
    - name: Unarchiving {{ nats_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ nats_tmp_zip }}'
        dest: '{{ nats_parent_install_dir }}'
        creates: '{{ nats_install_dir }}'
  always:
    - name: Rm {{ nats_tmp_zip }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ nats_tmp_zip }}'
        state: absent
- name: Linking {{ nats_link_dir }} to {{ nats_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ nats_install_dir }}'
    dest: '{{ nats_link_dir }}'
    state: link
- name: Include in shell...
  become: true
  become_user: root
  with_items:
    - t: nats.sh.j2
      f: '{{ nats_app }}.sh'
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.t }}'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
